### PR TITLE
Add support for OpenBSD

### PR DESCRIPTION
**Pull request by brad0**

### CODE REVIEW

**Comment by compudj** [comment]
Can you provide a short commit message, along with your Signed-off-by tag please ?

**Comment by brad0** [comment]
> Can you provide a short commit message, along with your Signed-off-by tag please ?

What should I have in said message?

**Comment by compudj** [comment]
Please provide a bit of context, e.g. "Use the __OpenBSD__ define to detect build on OpenBSD. Use the same approach to what is done for FreeBSD for the syscall-compat header, rely on pthread cond variables for futex compatibility, and use getthrid() to implement urcu_get_thread_id(). This has been build and runtime tested on OpenBSD X.Y on architecture <insert arch name here>.".

I wonder if using pthread cond variables for futex compatibility is really the best we can do here, or if openbsd provides something similar to _umtx_op from FreeBSD ?

**Comment by brad0** [comment]
> rely on pthread cond variables for futex compatibility
>
> I wonder if using pthread cond variables for futex compatibility is really the best we can do here, or if openbsd provides something similar to _umtx_op from FreeBSD ?

I wasn't sure what you meant by this at first so I went looking around. I see. OpenBSD uses futex's.

**Comment by compudj** [comment]
Relying on pthread cond var is fine for the initial patch. I agree that wiring up futexes on openbsd can come as a separate patch.

**Comment by compudj** [comment]
merged manually into master, thanks!

**Comment by brad0** [comment]
Can this also be backported to the 14 and 13 branches?

**Comment by brad0** [comment]
ping.

**Comment by compudj** [comment]
I now notice that OpenBSD was listed as "Should also work" in the README file. I'm backporting those as bug fixes into 0.13 and 0.14. Thanks!

**Comment by brad0** [comment]
> I now notice that OpenBSD was listed as "Should also work" in the README file. I'm backporting those as bug fixes into 0.13 and 0.14. Thanks!

Thanks.

**Pull request closed without merging**
